-- VHDL Entity fahim_segment_lib.tb_finalsegment.symbol
--
-- Created:
--          by - user.UNKNOWN (KTP12R7182)
--          at - 18:45:55 01/05/2018
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.2 (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

entity tb_finalsegment is
   port( 
      hour_dig1 : out    STD_LOGIC_VECTOR (3 downto 0);
      hour_dig2 : out    STD_LOGIC_VECTOR (3 downto 0);
      le        : out    std_logic;
      min_dig1  : out    STD_LOGIC_VECTOR (3 downto 0);
      min_dig2  : out    STD_LOGIC_VECTOR (3 downto 0);
      oe        : out    std_logic;
      sclk      : out    std_logic;
      sdi       : out    std_logic;
      sec_dig1  : out    STD_LOGIC_VECTOR (3 downto 0);
      sec_dig2  : out    STD_LOGIC_VECTOR (3 downto 0)
   );

-- Declarations

end tb_finalsegment ;

--
-- VHDL Architecture fahim_segment_lib.tb_finalsegment.struct
--
-- Created:
--          by - user.UNKNOWN (KTP12R7182)
--          at - 18:45:55 01/05/2018
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2016.2 (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

library fahim_segment_lib;

architecture struct of tb_finalsegment is

   -- Architecture declarations

   -- Internal signal declarations
   signal clk    : STD_LOGIC;
   signal reset  : STD_LOGIC;
   signal slider : STD_LOGIC;


   -- Component Declarations
   component tb_gclock_1
   port (
      clk       : in     STD_LOGIC ;
      reset     : in     STD_LOGIC ;
      slider    : in     STD_LOGIC ;
      hour_dig1 : out    STD_LOGIC_VECTOR (3 downto 0);
      hour_dig2 : out    STD_LOGIC_VECTOR (3 downto 0);
      le        : out    std_logic ;
      min_dig1  : out    STD_LOGIC_VECTOR (3 downto 0);
      min_dig2  : out    STD_LOGIC_VECTOR (3 downto 0);
      oe        : out    std_logic ;
      sclk      : out    std_logic ;
      sdi       : out    std_logic ;
      sec_dig1  : out    STD_LOGIC_VECTOR (3 downto 0);
      sec_dig2  : out    STD_LOGIC_VECTOR (3 downto 0)
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : tb_gclock_1 use entity fahim_segment_lib.tb_gclock_1;
   -- pragma synthesis_on


begin
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1                                        
   slider<='0';

   -- HDL Embedded Text Block 3 clock_and_reset1
   -- eb1 1                                        
                                         
   process
   begin
     clk<='1';
     wait for 4 ns;
     clk<='0';
     wait for 4 ns;
   end process;
   process
   begin
     reset<='0';
   wait;
   end process;
   
   
   
   
   
   
   
   


   -- Instance port mappings.
   U_0 : tb_gclock_1
      port map (
         clk       => clk,
         reset     => reset,
         slider    => slider,
         hour_dig1 => hour_dig1,
         hour_dig2 => hour_dig2,
         le        => le,
         min_dig1  => min_dig1,
         min_dig2  => min_dig2,
         oe        => oe,
         sclk      => sclk,
         sdi       => sdi,
         sec_dig1  => sec_dig1,
         sec_dig2  => sec_dig2
      );

end struct;
